In [3]:
import pandas as pd 
import numpy as np 
import sqlite3
print ("Library_Imported")

Library_Imported

In [4]:
category = pd.read_csv("C:/Users/adity/Downloads/ecommerce_sql_database_csv/categories1.csv")
customers = pd.read_csv("C:/Users/adity/Downloads/ecommerce_sql_database_csv/customers.csv")
order_items = pd.read_csv("C:/Users/adity/Downloads/ecommerce_sql_database_csv/order_items.csv")
orders = pd.read_csv("C:/Users/adity/Downloads/ecommerce_sql_database_csv/orders.csv")
payments = pd.read_csv("C:/Users/adity/Downloads/ecommerce_sql_database_csv/payments.csv")
products = pd.read_csv("C:/Users/adity/Downloads/ecommerce_sql_database_csv/products.csv")
reviews = pd.read_csv("C:/Users/adity/Downloads/ecommerce_sql_database_csv/reviews.csv")
sellers = pd.read_csv("C:/Users/adity/Downloads/ecommerce_sql_database_csv/sellers.csv")

In [5]:
display(category.head(5))
display(customers.head(5))
display(order_items.head(10))
display(orders.head(10))
display(payments.head(5))
display(products.head(5))
display(reviews.head(5))
display(sellers.head(5))

        0       category_name  Unnamed: 2  bvgchjzxbCn
0  CAT001        Electronics          NaN          NaN
1  CAT002  Mobile Accessories         NaN          NaN
2  CAT003             Laptops         NaN          NaN
3  CAT004     Home Appliances         NaN          NaN
4  CAT005             Kitchen         NaN          NaN

,CUSTOMER_id,first_name,last_name,gendER,city,age,signup_date,email
0,CUST00001,Kavya,Yadav,Other,Pune,47,16-03-2020 00:00,kavya.yadav1@example.com
1,CUST00001,Kavya,Yadav,Other,Pune,47,16-03-2020 00:00,kavya.yadav1@example.com
2,CUST00003,Neha,Jain,Female,Indore,35,28-02-2021 00:00,neha.jain3@example.com
3,CUST00004,Aman,Kapoor,Female,Pune,25,23-09-2021 00:00,aman.kapoor4@example.com
4,CUST00005,Rohan,Verma,Male,Nagpur,46,22-06-2022 00:00,rohan.verma5@example.com

,order_item_id,order_id,product_id,quantity,unit_price,item_discount,line_total
0,OI0000001,ORD044190,PROD01129,1,246.71,0.177,203.04
1,OI0000002,ORD044290,PROD00240,1,663.98,0.067,619.49
2,OI0000003,ORD047965,PROD01129,4,246.71,0.134,854.60
3,OI0000004,ORD001635,PROD01673,4,400.50,0.183,1308.83
4,OI0000005,ORD040675,PROD00842,3,653.40,0.016,1928.84
5,OI0000006,ORD008949,PROD01615,1,1037.48,0.017,1019.84
6,OI0000007,ORD022365,PROD00276,3,815.53,0.066,2285.12
7,OI0000008,ORD015614,PROD01600,4,3817.13,0.024,14902.08
8,OI0000009,ORD018105,PROD01318,5,4352.85,0.159,18303.73
9,OI0000010,ORD013577,PROD00604,2,2713.63,0.125,4748.85

,order_id,customer_id,order_date,order_status,shipping_city,discount,shipping_fee
0,ORD000001,CUST04430,2025-08-27 09:38:00,Delivered,Chennai,0.250,161.64
1,ORD000002,CUST08917,2024-03-17 01:24:00,Returned,Mumbai,0.226,86.64
2,ORD000003,CUST01242,2024-07-20 13:57:00,Cancelled,Nagpur,0.190,215.26
3,ORD000004,CUST01873,2025-03-12 09:49:00,Cancelled,Bangalore,0.222,220.38
4,ORD000005,CUST08842,2023-05-07 06:58:00,Delivered,Nagpur,0.298,213.06
5,ORD000006,CUST05217,2025-10-15 20:41:00,Processing,Indore,0.190,74.74
6,ORD000007,CUST05349,2025-03-31 23:36:00,Delivered,Indore,0.161,187.23
7,ORD000008,CUST05529,2025-12-24 22:02:00,Delivered,Kolkata,0.295,116.94
8,ORD000009,CUST02598,2024-11-25 14:56:00,Delivered,Chennai,0.110,161.84
9,ORD000010,CUST04005,2025-01-08 04:20:00,Shipped,Mumbai,0.283,59.54

  payment_id   order_id    payment_method payment_status  payment_amount
0  PAY000001  ORD000001       Credit Card           Paid         9797.53
1  PAY000002  ORD000002               UPI           Paid        22167.80
2  PAY000003  ORD000003        Debit Card           Paid        24513.06
3  PAY000004  ORD000004  Cash on Delivery           Paid        19102.81
4  PAY000005  ORD000005       Net Banking           Paid         8259.71

,product_id,product_name,category_id,seller_id,unit_price,cost_price,stock_quantity
0,PROD00001,Product_00001,CAT007,SEL0024,733.19,599.54,312
1,PROD00002,Product_00002,CAT018,SEL0683,8310.91,4022.57,661
2,PROD00003,Product_00003,CAT009,SEL0109,2788.72,1385.10,943
3,PROD00004,Product_00004,CAT006,SEL0210,1543.19,1038.40,203
4,PROD00005,Product_00005,CAT070,SEL0607,3552.81,1664.71,221

,review_id,customer_id,product_id,rating,review_date,review_text
0,REV000001,CUST07933,PROD00547,3,2023-05-28 00:00:00,Review text 000001
1,REV000002,CUST04185,PROD01984,4,2024-03-02 00:00:00,Review text 000002
2,REV000003,CUST02323,PROD01863,4,2025-08-02 00:00:00,Review text 000003
3,REV000004,CUST05616,PROD01545,5,2023-12-17 00:00:00,Review text 000004
4,REV000005,CUST09165,PROD00598,4,2024-04-06 00:00:00,Review text 000005

  seller_id  seller_name       city  seller_rating            join_date
0   SEL0001  Seller_0001    Chennai           3.14  2021-10-28 00:00:00
1   SEL0002  Seller_0002       Pune           4.32  2021-04-24 00:00:00
2   SEL0003  Seller_0003    Kolkata           3.98  2019-03-28 00:00:00
3   SEL0004  Seller_0004  Bangalore           2.76  2024-09-21 00:00:00
4   SEL0005  Seller_0005    Chennai           4.80  2020-02-12 00:00:00

In [6]:
category = category.drop(columns =["bvgchjzxbCn","Unnamed: 2"])

In [7]:
print(category.shape)
print(customers.shape)
print(order_items.shape)
print(orders.shape)
print(payments.shape)
print(products.shape)
print(reviews.shape)
print(sellers.shape)

(100, 2)
(10000, 8)
(150000, 7)
(50000, 7)
(50000, 5)
(2000, 7)
(30000, 6)
(1000, 5)

In [8]:
category = category.drop_duplicates()
customers= customers.drop_duplicates()
order_items = order_items.drop_duplicates()
orders = orders.drop_duplicates()
payments = payments.drop_duplicates()
products = products.drop_duplicates()
reviwes = reviews.drop_duplicates()
sellers = sellers.drop_duplicates()

In [9]:
print(category.shape)
print(customers.shape)
print(order_items.shape)
print(orders.shape)
print(payments.shape)
print(products.shape)
print(reviews.shape)
print(sellers.shape)

(100, 2)
(9999, 8)
(150000, 7)
(50000, 7)
(50000, 5)
(2000, 7)
(30000, 6)
(1000, 5)

In [13]:
tables = {
    "category": category,
    "customers": customers,
    "order_items": order_items,
    "orders": orders,
    "payments": payments,
    "products": products,
    "reviews": reviews,
    "sellers": sellers
}

for name, df in tables.items():
    print(f"\n{name}")
    print(df.isnull().sum())
    tables[name]= df.fillna("NA")

category
0                0
category_name    0
dtype: int64

customers
CUSTOMER_id    0
first_name     0
last_name      0
gendER         0
city           0
age            0
signup_date    0
email          0
dtype: int64

order_items
order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
item_discount    0
line_total       0
dtype: int64

orders
order_id         0
customer_id      0
order_date       0
order_status     0
shipping_city    0
discount         0
shipping_fee     0
dtype: int64

payments
payment_id        0
order_id          0
payment_method    0
payment_status    0
payment_amount    0
dtype: int64

products
product_id        0
product_name      0
category_id       0
seller_id         0
unit_price        0
cost_price        0
stock_quantity    0
dtype: int64

reviews
review_id      0
customer_id    0
product_id     0
rating         0
review_date    0
review_text    0
dtype: int64

sellers
seller_id        0
seller_name      0
city             0
seller_rating    0
join_date        0
dtype: int64

In [12]:
orders["shipping_fee"] = orders["shipping_fee"].fillna(0)

In [129]:
tables = {
    "category": category,
    "customers": customers,
    "order_items": order_items,
    "orders": orders,
    "payments": payments,
    "products": products,
    "reviews": reviews,
    "sellers": sellers
}

for name, df in tables.items():
    print(f"\n{name}")
    print(df.dtypes)

category
0                str
category_name    str
dtype: object

customers
CUSTOMER_id      str
first_name       str
last_name        str
gendER           str
city             str
age            int64
signup_date      str
email            str
dtype: object

order_items
order_item_id        str
order_id             str
product_id           str
quantity           int64
unit_price       float64
item_discount    float64
line_total       float64
dtype: object

orders
order_id             str
customer_id          str
order_date           str
order_status         str
shipping_city        str
discount         float64
shipping_fee     float64
dtype: object

payments
payment_id            str
order_id              str
payment_method        str
payment_status        str
payment_amount    float64
dtype: object

products
product_id            str
product_name          str
category_id           str
seller_id             str
unit_price        float64
cost_price        float64
stock_quantity      int64
dtype: object

reviews
review_id        str
customer_id      str
product_id       str
rating         int64
review_date      str
review_text      str
dtype: object

sellers
seller_id            str
seller_name          str
city                 str
seller_rating    float64
join_date            str
dtype: object

In [130]:
orders["shipping_fee"] = orders["shipping_fee"].fillna(0)
print(orders["shipping_fee"].isnull().sum())

0

In [144]:
sellers["join_date"] = pd.to_datetime(sellers["Join_Date"])
print(sellers.dtypes)
customers["signup_date"]=pd.to_datetime(customers["Signup_Date"])
print(customers.dtypes)
reviews["review_date"] = pd.to_datetime(reviews["Review_Date"])
print(reviews.dtypes)
orders["order_date"] = pd.to_datetime(orders["Order_Date"])
print(orders.dtypes)

Seller_Id                   str
Seller_Name                 str
City                        str
Seller_Rating           float64
Join_Date        datetime64[us]
join_date        datetime64[us]
dtype: object
Customer_Id               str
First_Name                str
Last_Name                 str
Gender                    str
City                      str
Age                     int64
Signup_Date    datetime64[us]
Email                     str
signup_date    datetime64[us]
dtype: object
Review_Id                 str
Customer_Id               str
Product_Id                str
Rating                  int64
Review_Date    datetime64[us]
Review_Text               str
review_date    datetime64[us]
dtype: object
Order_Id                    str
Customer_Id                 str
Order_Date       datetime64[us]
Order_Status                str
Shipping_City               str
Discount                float64
Shipping_Fee            float64
order_date       datetime64[us]
dtype: object

In [132]:
category.columns = category.columns.str.strip().str.title()
customers.columns = customers.columns.str.strip().str.title()
order_items.columns = order_items.columns.str.strip().str.title()
orders.columns = orders.columns.str.strip().str.title()
payments.columns = payments.columns.str.strip().str.title()
products.columns = products.columns.str.strip().str.title()
reviews.columns = reviews.columns.str.strip().str.title()
sellers.columns = sellers.columns.str.strip().str.title()

In [133]:
print(customers["Customer_Id"].isin(orders["Customer_Id"]).value_counts())

Customer_Id
True     9933
False      66
Name: count, dtype: int64

In [134]:
orders["Customer_Id"].isin(customers["Customer_Id"]).value_counts()

Customer_Id
True     49995
False        5
Name: count, dtype: int64

In [135]:
for name, df in tables.items():
    print(name)
    print(df.describe())

category
             0       Category_Name
count      100                 100
unique     100                  21
top     CAT001  Mobile Accessories
freq         1                   5
customers
               Age                 Signup_Date
count  9999.000000                        9999
mean     41.400840  2022-10-18 10:26:27.758776
min      18.000000         2019-01-01 00:00:00
25%      30.000000         2020-11-19 12:00:00
50%      41.000000         2022-10-15 00:00:00
75%      53.000000         2024-09-18 00:00:00
max      65.000000         2026-08-31 00:00:00
std      13.821843                         NaN
order_items
            Quantity     Unit_Price  Item_Discount     Line_Total
count  150000.000000  150000.000000  150000.000000  150000.000000
mean        2.999927    2072.709015       0.100006    5590.797523
std         1.415959    2795.942240       0.057797    8784.361145
min         1.000000     100.000000       0.000000      80.100000
25%         2.000000     640.450000       0.050000    1333.517500
50%         3.000000    1253.890000       0.100000    2977.595000
75%         4.000000    2417.050000       0.150000    6411.387500
max         5.000000   41635.990000       0.200000  207139.050000
orders
                       Order_Date      Discount  Shipping_Fee
count                       50000  50000.000000  50000.000000
mean   2024-07-02 09:11:41.724000      0.149469    124.546852
min           2023-01-01 00:02:00      0.000000      0.000000
25%           2023-10-04 07:58:15      0.074000     61.670000
50%           2024-07-04 06:15:30      0.150000    124.585000
75%           2025-03-31 00:59:15      0.224000    187.250000
max           2025-12-30 23:30:00      0.300000    250.000000
std                           NaN      0.086618     72.364601
payments
       Payment_Amount
count    50000.000000
mean     12587.975375
std       7151.803170
min        200.180000
25%       6433.382500
50%      12551.030000
75%      18767.642500
max      24999.300000
products
         Unit_Price    Cost_Price  Stock_Quantity
count   2000.000000   2000.000000     2000.000000
mean    1875.859845   1348.181590      506.751500
std     2991.504945   1866.748253      289.117765
min   -24063.260000     47.520000        1.000000
25%      561.955000    395.545000      254.750000
50%     1161.485000    813.415000      516.000000
75%     2280.042500   1597.472500      755.000000
max    41635.990000  23545.570000      999.000000
reviews
             Rating                 Review_Date
count  30000.000000                       30000
mean       3.921467  2024-07-01 02:26:55.680000
min        1.000000         2023-01-01 00:00:00
25%        3.000000         2023-10-03 00:00:00
50%        4.000000         2024-07-01 00:00:00
75%        5.000000         2025-03-30 00:00:00
max        6.000000         2025-12-30 00:00:00
std        1.161469                         NaN
sellers
       Seller_Rating                   Join_Date
count    1000.000000                        1000
mean        3.756750  2022-12-18 08:48:28.800000
min         2.500000         2019-01-01 00:00:00
25%         3.137500         2021-02-23 06:00:00
50%         3.790000         2023-01-05 00:00:00
75%         4.370000         2024-10-24 12:00:00
max         5.000000         2026-08-28 00:00:00
std         0.710451                         NaN

In [136]:
products[products["Stock_Quantity"] == 999]

,Product_Id,Product_Name,Category_Id,Seller_Id,Unit_Price,Cost_Price,Stock_Quantity
10,PROD00011,Product_00011,CAT070,SEL0743,-1089.73,717.55,999
35,PROD00036,Product_00036,CAT002,SEL0900,253.51,196.09,999
785,PROD00786,Product_00786,CAT081,SEL0552,234.97,128.89,999

In [137]:
bad = products[products["Cost_Price"] >  products["Unit_Price"]]
print((bad["Unit_Price"] <= 0).sum())

100

In [138]:
bad[["Unit_Price", "Cost_Price"]].head(10)

     Unit_Price  Cost_Price
10     -1089.73      717.55
29     -2495.18     1949.92
59     -1279.04     1002.73
73     -2310.52     1439.48
77      -628.07      482.36
89     -2206.67     1172.22
90     -1523.67      944.06
138     -986.83      838.69
142   -24063.26    16639.69
151     -600.48      476.93

In [139]:
 products["Unit_Price"] =  products["Unit_Price"].abs()

In [142]:
print (customers["City"].value_counts())

City
Nagpur       1071
Pune         1045
Chennai      1040
Hyderabad    1015
Indore       1000
Kolkata      1000
Delhi         970
Bangalore     954
Raipur        954
Mumbai        950
Name: count, dtype: int64

In [141]:
customers["City"] = customers["City"].str.strip().str.title()

In [16]:
customers.to_csv("customer.csv",index = False)
orders.to_csv("orders.csv",index = False)
products.to_csv("product.csv",index = False)
reviews.to_csv("review.csv",index = False)
sellers.to_csv("seller.csv",index = False)
category.to_csv("category.csv",index = False)
payments.to_csv("payment.csv",index = False)
order_items.to_csv("order_item.csv",index = False)